echo SOURCED: C-TAP-YOUR-SYSCONF-example.h.sh

#if we reuse bitmaps, make sure here to specify the BITMAPS_DIR_NAME!
REUSE_BMPS=yes
FAST_FILESYS_DIR_IF_USED="/media/seth/CTAP"
BITMAPS_DIR_NAME="SMALLbitmaps"
BITMAPS_PARENT_DIR=$FAST_FILESYS_DIR_IF_USED
BITMAPS_DIR="${BITMAPS_PARENT_DIR}/${BITMAPS_DIR_NAME}"
